### ISSUE TITLE
Mapbox Tile Picker needs to allow for picking multiple tiles

### ISSUE THREAD

**Issue by roblabs** [roblabs/ios-map-ui#11]
This commit, 5ca8ee4f9195ef3f6c6be562df3f2a9f41a00612, adds a tile picker in Mapbox.  But it needs improvements.

* The current grid has four polygons each with a `properties` attribute of `name`:  
  * `southwest`, `southeast`, `northwest`, `northeast`
* UI flow
  * when user clicks on a grid, the chosen grid should be highlighted, either by changing the color or the opacity
  * Tapping on the same grid when highlighted, should turn _off_ any highlighting
  * Grids not tapped should be grayed out, or clearly marked as not on, either by changing the color or the opacity
  * Any subsequent grid chosen should also be highlighted
* `gridList` is an array that tracks the list of grids tapped by `name`

There is likely a proper way to use a `NSPredicate` with a string that makes sense with a Mapbox layer to properly filter the grids that were tapped.  Then set the color & opacity appropriately.

Mapbox references

* https://docs.mapbox.com/ios/api/maps/5.9.0/predicates-and-expressions.html
* https://github.com/mapbox/mapbox-gl-native-ios/blob/master/platform/ios/docs/guides/For%20Style%20Authors.md#expression-operators

---

<img src="https://user-images.githubusercontent.com/118112/89361686-bb044a80-d680-11ea-907b-254fc1c24989.gif" width="400">

**Comment by roblabs** [comment]
Another way to look at the problem of highlighting polygons in Mapbox using `NSPredicate`.  Say I have a list of polygons with a `name` attribute.  And I have two arrays:  a list of Islands, and a list of Islands where there is good camping sites.

```swift
var sanJuanIslands = ["Orcas", "Jones", "Sucia", "Matia", "Stuart", "Johns"]

var goodCampingIslands = ["Jones", "Sucia", "Matia"]
```

### What is the best way to style _Good Camping Islands_ using `NSPredicate`?

* Goal: fill `goodCampingIslands` with a red fill at 50% opacity, while leaving the other Islands styled as black with 10% opacity.  

```swift
 layer.fillColor = NSExpression(forConstantValue: UIColor(red: 1, green: 0, blue: 0, alpha: 0.5))
 layer.predicate = NSPredicate(format: "name = %@", $0) // this is the current `NSPredicate`
```

---

![sanjuans polygons](https://user-images.githubusercontent.com/118112/89450909-3234ef80-d710-11ea-9e00-4b0cf96c5125.png)

**Comment by roblabs** [comment]
From Mapbox Support:

> If you would like to use arrays within your predicate, you can use the following syntax:

```swift
layer.predicate = NSPredicate(format: "name IN %@", goodCampingIslands)
```

> If you want different opacities or colors you would either need to create a new layer or use an NSExpression like the one below to set different values for each island name: 

```swift
layer.fillColor = NSExpression(format: "MGL_MATCH(name, 'Matia', %@, 'Sucia', %@, 'Jones', %@, %@)",
                                         UIColor.white, UIColor.purple, UIColor.gray, UIColor.red)
```
​
---

* Related discussion — https://stackoverflow.com/a/61328685

**Comment by roblabs** [comment]
Based on the suggestions from Mapbox Support, the following has been tried.  

This isn't quite working yet, and we are open to suggestions based on what has been tried.


### 1. `NSExpression` with hard coded array of islands to color red

This works, but this is not ideal as the list of items needs to be generated from a list of `goodCampingIslands = ["Jones", "Sucia", "Matia"]`

```swift
layer.fillColor = NSExpression(format: "MGL_MATCH(name, %@, %@, %@, %@, %@)",
                                       "Johns", UIColor.red, "Matia", UIColor.red, UIColor.gray)
```

![nsexperssions](https://user-images.githubusercontent.com/118112/90211583-f819bc80-dda5-11ea-84b7-baf94ef382d0.png)


---

### 2. Two `NSExpressions` only properly colors the most recent properly

```swift
layer.fillColor = NSExpression(format: "MGL_MATCH(name, %@, %@, UIColor.gray)", "Johns", UIColor.red
layer.fillColor = NSExpression(format: "MGL_MATCH(name, %@, %@, UIColor.gray)", "Matia", UIColor.red
```

---

### 3.  Ideally would like to generate the expression from an the array of `goodCampingIslands `

This _fails_ and only paints the last element of the array as red (similar to `#2`)

```swift
goodCampingIslands.forEach {
  layer.fillColor = NSExpression(format: "MGL_MATCH(name, %@, %@, UIColor.gray)", $0, UIColor.red
}
  
```

---

### 4. Using NSExpression with `init(forAggregate:)`

This is closer to allowing to build the Expressions in a loop.

```swift 
let johns = NSExpression(format: "MGL_MATCH(name, %@, %@, UIColor.gray)", "Johns", UIColor.red)
let matia = NSExpression(format: "MGL_MATCH(name, %@, %@, UIColor.gray)", "Matia", UIColor.red)

layer.fillColor = NSExpression(forAggregate: [johns, matia])
```

**Comment by 1ec5** [comment]
> ```swift
> layer.fillColor = NSExpression(format: "MGL_MATCH(name, %@, %@, %@, %@, %@)",
>                                        "Johns", UIColor.red, "Matia", UIColor.red, UIColor.gray)
> ```

Consider using a conditional expression instead of a match expression in this case. The `TERNARY()` syntax is poorly documented, but it corresponds to the built-in `NSExpression(forConditional:trueExpression:falseExpression:)` initializer:

```swift
layer.fillColor = NSExpression(format: "TERNARY(name in %@, %@, %@)", goodCampingIslands, UIColor.red, UIColor.gray)
```

If you need a match expression because there are multiple output values, but you don’t know all the cases statically in advance, you can use `NSExpression(forMGLMatchingKey:in:default:)` to avoid manually building a format string through string concatenation. You’d need to provide a dictionary mapping inputs to outputs, as well as a default value. There’s an example of it in the suggestion in https://github.com/mapbox/mapbox-navigation-ios/pull/2535#discussion_r470330971.

**Comment by roblabs** [comment]
The `TERNARY` test with the array was the correct solution.  That ended up being the elegant way to solve this.

### Goal

Given a set of arbitrary shaped grids defined in a GeoJSON
* Initially paint all grids Gray
* Allow user to tap on a grid to toggle the choice, Red is selected, Gray is deselected

```swift
let sanJuanIslands = ["Orcas", "Jones", "Sucia", "Matia", "Stuart", "Johns"] // main list with some San Juan Islands
let goodCampingIslands = ["Jones", "Sucia", "Matia"] // Where to Camp in the San Juans

// set colors based on an array
layer.fillColor = NSExpression(format: "TERNARY(name in %@, %@, %@)", goodCampingIslands, UIColor.red, UIColor.gray)
// Be sure to keep all grids drawn on the map
layer.predicate = NSPredicate(format: "name IN %@", sanJuanIslands)

```

---

Thanks to @ZiZasaurus & @1ec5 for the advice via Mapbox Support and this discussion.  

---

![11](https://user-images.githubusercontent.com/118112/90280324-94cc7080-de1f-11ea-99c5-abbca2035e5f.gif)

**Comment by roblabs** [comment]
Fixed in https://github.com/roblabs/ios-map-ui/commit/c54a222f1978cfa80423e952e0ea4bcc8175b8ec
